title: Duel Links Meta
url: https://alphadkayed.netlify.com
disqus:
  shortname: duellinksmeta
exclude: ["Gemfile",
          "Gemfile.lock",
          "node_modules",
          ".gitignore",
          "package.json",
          "package-lock.json",
          "gulpfile.js"]
collections:
  admin:
    output: true
plugins:
  - jekyll-timeago
  - jekyll-angular
  - jekyll-sitemap
loadSize: 10
season-end: 0001-01-01T01:00:00.000
ga-url: alphadkayed.netlify.com
ga-code: UA-93155050-2
incremental: true