title: Duel Links Meta
url: https://dlmbeta.netlify.com
disqus:
  shortname: duellinksmeta
exclude: ["Gemfile",
          "Gemfile.lock",
          "node_modules"]
collections:
  authors:
    output: true
    permalink: /:collection/:name
  admin:
    output: true
plugins:
  - jekyll-timeago
  - jekyll-angular
  - jekyll-sitemap
include: ['.htaccess', '_headers']
season-end: 0001-01-01T01:00:00.000