title: Duel Links Meta
url: https://dlmbeta.netlify.com
disqus:
  shortname: duellinksmeta
exclude:
    - node_modules
collections:
  authors:
    output: true
    permalink: /:collection/:name
  admin:
    output: true
gems:
  - jekyll-timeago
  - jekyll-angular
plugins-dir:
  - jekyll-sitemap
include: ['.htaccess', '_headers']
season-end: 0001-01-01T01:00:00.000