title: Duel Links Meta
url: https://duellinksmeta.netlify.com
disqus:
  shortname: duellinksmeta
exclude:
    - node_modules
collections:
  authors:
    output: true
    permalink: /:collection/:name
  decklists:
    output: true
gems:
  - jekyll-timeago